# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fastapi-service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://fastapiregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_785c95e0f60a4ffba047312b4215f69d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_bf6acddd9dab48ccbe96df1cb85274df }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: fastapiregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_785c95e0f60a4ffba047312b4215f69d }}/sampleapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fastapi-service'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b7d6f81b103844c8868e935faad2b099 }}
        images: 'fastapiregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_785c95e0f60a4ffba047312b4215f69d }}/sampleapp:${{ github.sha }}'